### PR TITLE
SVGKLayer: remove observer that causes a crash in dealloc.

### PR DESCRIPTION
**Pull request by laurakart**

### CODE REVIEW

**Comment by RonItzhak** [comment]
@joemuers We recently added SVGKit to Facetune, and noticed that when an SVGK*ImageView is dealloced, the app crashes. Looking at the code we saw this bizarre decision by the original writers that seem to know of the crash, but decided to only doc it instead of adding the solution they themselves provide in the doc...
Have you ever come across this? Has this not been a problem for your uses?

**Comment by joemuers** [comment]
> @joemuers We recently added SVGKit to Facetune, and noticed that when an SVGK*ImageView is dealloced, the app crashes. Looking at the code we saw this bizarre decision by the original writers that seem to know of the crash, but decided to only doc it instead of adding the solution they themselves provide in the doc...
> Have you ever come across this? Has this not been a problem for your uses?

No this is the first I've heard about this. Nothing's come up in Crashlytics that we've noticed.
We never really use SVGKit, for us it's only there because we have some legacy code that depends on it. Is there some reason you directed this question at me in particular?  As TBH I know very little about this library.

**Comment by RonItzhak** [comment]
> > @joemuers We recently added SVGKit to Facetune, and noticed that when an SVGK*ImageView is dealloced, the app crashes. Looking at the code we saw this bizarre decision by the original writers that seem to know of the crash, but decided to only doc it instead of adding the solution they themselves provide in the doc...
> > Have you ever come across this? Has this not been a problem for your uses?
> 
> No this is the first I've heard about this. Nothing's come up in Crashlytics that we've noticed. We never really use SVGKit, for us it's only there because we have some legacy code that depends on it. Is there some reason you directed this question at me in particular? As TBH I know very little about this library.

I just saw that you were the last person to touch this repo. 
So there should be no problem with merging this then. 

Thanks!

**Comment by joemuers** [comment]
> > > @joemuers We recently added SVGKit to Facetune, and noticed that when an SVGK*ImageView is dealloced, the app crashes. Looking at the code we saw this bizarre decision by the original writers that seem to know of the crash, but decided to only doc it instead of adding the solution they themselves provide in the doc...
> > > Have you ever come across this? Has this not been a problem for your uses?
> > 
> > 
> > No this is the first I've heard about this. Nothing's come up in Crashlytics that we've noticed. We never really use SVGKit, for us it's only there because we have some legacy code that depends on it. Is there some reason you directed this question at me in particular? As TBH I know very little about this library.
> 
> I just saw that you were the last person to touch this repo. So there should be no problem with merging this then.
> 
> Thanks!

Ah right, yeah I think that was just to silence a couple of build time warnings the library was throwing up for us, but nothing functional. 
All good, I'm sure you're fine to merge.

**Pull request merged**
